services:
  classifiation-api:
    container_name: ner-linking-api
    build: .
    user: root
    environment:
      DICTIONARY_FILE:
      LANGUAGE: es
    ports:
      - 8002:8000
    volumes:
      - .:/app
    restart: unless-stopped
    privileged: true
    command: flask run --host=0.0.0.0 --port=8000

networks:
  default:
    name: cogstack-net
    external: true
